#--------- This file is automatically generated by LSST's sconsUtils ---------#
__version__ = 'unknown'
__repo_version__ = 'unknown'
__repo_version__ = 'unknown'
__fingerprint__ = '0x0'
__dependency_versions__ = {
    'boost': '1.59.lsst5',
    'python': 'unknown',
    'boost_regex': '1.59.lsst5',
    'base': '2015_10.0-1-g1d153f6+9',
    'pex_exceptions': '2015_10.0-1-gf7aee88+9',
    'numpy': '0.0.1+5',
    'utils': '2015_10.0-3-g530cd83+7',
    'boost_system': '1.59.lsst5',
    'boost_filesystem': '1.59.lsst5',
    'daf_base': '2015_10.0-3-g4d32b56+7',
    'pex_logging': '2015_10.0-1-gf6c85b3+9',
    'pex_policy': '2015_10.0-1-gd4eb80a+10',
    'pex_config': '2015_10.0-1-gc006da1+9',
    'mysqlclient': '5.1.73.lsst3',
    'boost_serialization': '1.59.lsst5',
    'daf_persistence': '2015_10.0-5-g4063539+7',
    'pipe_base': '2015_10.0-3-g24e103a+8',
}
__all__ = ('__version__', '__repo_version__', '__repo_version__', '__fingerprint__', '__dependency_versions__')
